apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Example configuration for the webserver
# at https://github.com/monopole/hello
resources:

#- https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/examples/helloWorld/configMap.yaml
- configMap.yaml
#- https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/examples/helloWorld/deployment.yaml
- deployment.yaml
#- https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/examples/helloWorld/service.yaml
- service.yaml
metadata:
  name: hello-world
namespace: kustomize-test
commonLabels:
  someName: demo-demo
#patch json6902 demo replace
patches:
- path: overlays/edit-value.yaml
  target:
      kind: Deployment
      name: the-deployment