apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Example configuration for the webserver
# at https://github.com/monopole/hello
resources:

#- https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/examples/helloWorld/configMap.yaml
- base/configMap.yaml
#- https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/examples/helloWorld/deployment.yaml
- base/deployment.yaml
#- https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/examples/helloWorld/service.yaml
- base/service.yaml
metadata:
  name: hello-world
namespace: kustomize-test
commonLabels:
  someName: demo-demo

#patch json6902 demo replace
patchesJson6902:
- path: ../overlays/change-replicas.yaml
  target:
      version: v1
      kind: Deployment
      name: the-deployment