apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases: 
- ../base

#patch json6902 demo replace
patchesJson6902:
 - target:
      version: v1
      kind: Deployment
      name: the-deployment
   patch: |-
      - op: replace
        path: /spec/replicas
        value: 1