apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- base/argo-cd-ui-ingress.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patchesStrategicMerge:
- overlays/argocd-server-service.yaml

patchesJson6902:
- path: overlays/argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1
patches:
- path: overlays/argo-cd-ui-ingress.yaml
  target:
    kind: Ingress
    name: argocd-server-http-ingress

namespace: argocd